
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/soft/cmake-3.28.0-windows-x86_64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
...
